name: Portfolio CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify Portfolio
        run: echo "Portfolio workflow ran successfully!"